global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'
  
receivers:
- name: 'email'
  email_configs:
  - to: 'stefinitu@gmail.com'
    from: 'mylifeisempty1234@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'mylifeisempty1234@gmail.com'
    auth_identity: 'mylifeisempty1234@gmail.com'
    auth_password: 'jgpuhjelbizkfyuo'
